# Site configuration
title: Welcome to my Blog
email: geckocore03@outlook.com
description: Just to share what I've learned
baseurl: ""
url: ""

# Build settings
markdown: kramdown

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

# Owner information
owner:
    name: Antonio Campos
    bio: >
        22 years old, Computer science student, another carbon piece.
        I enjoy programming and listening to music, I'm currently focused
        on creating custom user interfaces also I find functional programming
        pretty interesting and I really like learning something new: a language or framework.
    interests: [C++ (Qt), C# (WPF), Python, Haskell]
    avatar_hash: cff3e11c78e0e1068164741c02d2c186
    job: Student
    email: geckocore03@outlook.com
    twitter: glxnull
    facebook: shellgecko
    github: glxnull
    instagram: glxnull
    lastfm: shellgecko

# Gems
gems:
  - jekyll-feed
  - github-pages

exclude: [Gemfile, Gemfile.lock, package.json, yarn.lock, node_modules, gulpfile.js]
